### ISSUE TITLE
Mancanza doppia lingua

### ISSUE THREAD

**Issue by bam965** [ITPUG/2017.pgday.it#12]
Manca la doppia lingua per le descrizioni qui:

- https://github.com/ITPUG/2017.pgday.it/blob/master/_data/sessions.yml
qui basta la doppia lingua per titolo e descrizione

- https://github.com/ITPUG/2017.pgday.it/blob/master/_data/speakers.yml
qui basta la doppia lingua per la bio ed il titolo 

- https://github.com/ITPUG/2017.pgday.it/blob/master/_data/schedule.yml
qui basta la doppia lingua per il campo "dateReadable:" riga 3

**Comment by mnencia** [comment]
Scusa, ma che senso ha avere il titolo dei talk e la descrizione in doppia lingua?

Sarà nella lingua del talk no?

**Comment by mnencia** [comment]
Per gli speaker, siamo sicuri di voler tradurre la biografia (che ci potrebbe anche stare) e il titolo (che secondo me è assurdo)? Secondo me devono rimanere come ce le hanno mandati gli speaker.

**Comment by mnencia** [comment]
fatto tutto fuori che la bio e il titolo degli speaker, che secondo me non è da fare
